### ISSUE TITLE
[BUG] 链接样式在Database Folder插件不兼容

### ISSUE THREAD

**Issue by ouatis** [subframe7536/obsidian-theme-maple#1]
**Describe the Bug**
链接样式与 [Database Folder](https://github.com/RafaelGB/obsidian-db-folder) 不兼容。后者可以表格化metadata，现在的链接样式会在每一格前加入自定义的文档icon，理论上这些格子都不是文档。希望能够兼容，非常感谢。

**Relevant Screenshots**
![Snipaste_2022-11-30_03-02-56](https://user-images.githubusercontent.com/53555223/204623392-41a78f14-9543-43ac-b200-bcd06e8e8bee.png)

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. 右键文件夹A
2. 点击New Database folder
3. 出现表格，看到问题

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [ ] Source Mode
- [ ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [ ] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [x] Insider Release (Desktop)
- [x] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
已修复

**Comment by Dayosama** [comment]
Hello, this bug is still there for me

**Comment by subframe7536** [comment]
fix in https://github.com/subframe7536/obsidian-theme-maple/commit/cdf3b35e6735eb1175e4d1ce680e965f33aed84a

**Comment by Dayosama** [comment]
So much reactivity 😍 Awesome thank you !!
By the way, just want to say that your theme is the best I ever tried !!
