### ISSUE TITLE
Feature Request: 标签页能否和标签页标题栏一样支持调整为小尺寸

### ISSUE THREAD

**Issue by cc1477** [subframe7536/obsidian-theme-maple#100]

**Comment by subframe7536** [comment]
有样例吗？我不太理解你说的意思

**Comment by cc1477** [comment]
> 有样例吗？我不太理解你说的意思
![mmexport1730525645299.png](https://github.com/user-attachments/assets/be344bac-3894-4965-b277-fdb3f838159c)
就是这个标签页可以支持调整为窄边框样式

**Comment by cc1477** [comment]
> 有样例吗？我不太理解你说的意思

还有标签页的字体大小也可以和标签页标题栏文件名一样支持小尺寸

**Comment by subframe7536** [comment]
关闭 “仿 Firefox / Microsoft Edge 的标签页” 试试

**Comment by cc1477** [comment]
> 关闭 “仿 Firefox / Microsoft Edge 的标签页” 试试
貌似不行

**Comment by subframe7536** [comment]
窄边框具体是什么样子的？和border的那种自动隐藏类似，还是说标签页降低整体高度？

最好给个样式的示意图

**Comment by cc1477** [comment]
> 窄边框具体是什么样子的？和border的那种自动隐藏类似，还是说标签页降低整体高度？
> 
> 最好给个样式的示意图

主要是标签页宽度和标签页字体大小吧，如果把 ob 的字体缩小的话这块 Ui 就特别大感觉很突兀，我电脑不在身边，你可以看着改改
