### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tinymacs** [subframe7536/obsidian-theme-maple#103]
**Describe the Bug**
macos15.1
style setting中修改链接的颜色后，编辑器中链接的颜色没有发生对应的变化，（链接会始终保持为蓝色，不发生变化）
反而，粗体和斜体的颜色会对应地变化（比如，在图中，他们变成了红色）

另外，有以下FR
关于链接颜色，有以下更加详细的颜色分类方案：
关于内链：
1. 废掉的，没有目标的内链
2. 创建好的，完整的内链
3. 鼠标放在内链上，高亮的内链
外链：同理。

此外，希望能增加按钮，让我能够自定义：
“是否显示内链的下划线”
“是否显示外链的下划线”

**Relevant Screenshots**
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/85ad46f9-52a4-492f-8205-ce2499076bad">

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/6ed1d257-0640-4a25-b4ec-cda615c677cd">

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/cb5b1178-f568-4232-8278-c3856baaa390">

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. style setting 中修改链接颜色（如图1）
2. 切回到文档编辑器中，发现内链和外链的颜色都没有发生变化

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview
三种显示情况下，我都不能更改内链和外链的颜色

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)

**Checklist**
- [x] **The bug can be reproduced in Sandbox Vault**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
感谢反馈，我抽空看一下

**Comment by subframe7536** [comment]
0.8.26已修复

下划线可以通过设置颜色来控制是否显示
