### ISSUE TITLE
[BUG]侧边栏文字大小在1.7.7版本后会和编辑器文字大小一起变化

### ISSUE THREAD

**Issue by ZoeyNya** [subframe7536/obsidian-theme-maple#104]
**Describe the Bug**
如题目所说的那样
侧边栏（文件夹管理、标签栏等等）文字大小在1.7.7版本下会和编辑器文字大小一起变化。
这样的话会显得有些不协调，希望侧边栏文字大小能自定义或是固定一个值

**Comment by subframe7536** [comment]
已修复，0.8.27 中现在不会出现这个问题了
