### ISSUE TITLE
Feature Request: Divider line for H1 to H6

### ISSUE THREAD

**Issue by dubefab** [subframe7536/obsidian-theme-maple#16]
Is it possible to add that option?
And is headers also had smaller line height ... 2.1 = insanely too big!

**Comment by subframe7536** [comment]
line height bug is been fixed in https://github.com/subframe7536/obsidian-theme-maple/commit/2efaf22548825d60d5d466c6b3325dac5b141de1
Divider line for H1 to H6... just like H2？
