### ISSUE TITLE
[BUG] 代码块显示问题

### ISSUE THREAD

**Issue by BonjourL** [subframe7536/obsidian-theme-maple#18]
代码块下  # 号很奇怪
<img width="261" alt="image" src="https://user-images.githubusercontent.com/37428385/223334167-5a9baddc-cb0c-4f31-b4df-88956cd92cad.png">

**Comment by subframe7536** [comment]
内嵌的 maple mono 字体特性，可以去 style settings 里设置为不使用，或者等宽字体特性中添加 cv01
