### ISSUE TITLE
Feature Request: Heading line height

### ISSUE THREAD

**Issue by dubefab** [subframe7536/obsidian-theme-maple#22]
Hey I find the line height way too high for my taste for headers.
Is it possible to weak it because the space seems weird to me.
Maybe I am wrong, if so, can you add an option to go from min to high or something like that?

<img width="719" alt="SC 2023-03-08 at 21 27 07@2x" src="https://user-images.githubusercontent.com/36094769/223917416-1c4a2c8e-63ce-4c4f-87a9-3634bcb79996.png">

**Comment by subframe7536** [comment]
As far as I know, css has no way of detecting whether an element is line wrapped, and only js can: https://stackoverflow.com/questions/75553437/can-modern-css-determine-whether-a-line-of-text-is-wrapped

and I think that long titles are unusual and inappropriate, so it maybe won't be fixed

**Comment by dubefab** [comment]
> As far as I know, css has no way of detecting whether an element is line wrapped, and only js can: https://stackoverflow.com/questions/75553437/can-modern-css-determine-whether-a-line-of-text-is-wrapped
> 
> and I think that long titles are unusual and inappropriate, so it maybe won't be fixed

OK I understand, if you compare with other themes though the height is twice as high!
I lead discussions and use headers to type in the questions and then have bullet points for possible answers, that's why I asked you to add the divider line to all the headers. It makes it clear to my brain that this is a question to ask. Often the questions take 2 lines... Thanks 😀

**Comment by subframe7536** [comment]
To ensure enough space for the divider under the title, you must increase the line height. Adding margin may cause some rows to be unclickable in certain cases. This is based on my multiple attempts.

**Comment by dubefab** [comment]
> To ensure enough space for the divider under the title, you must increase the line height. Adding margin may cause some rows to be unclickable in certain cases. This is based on my multiple attempts.

hmm that's too bad, then I preferred having no line and a normal line height (before yesterday's update the headers looked fine and followed my 1.5 line height setting). By the way, the high line height still happens when the divider is not being used...

**Comment by subframe7536** [comment]
I got the reason. something weired happen. 

![image](https://user-images.githubusercontent.com/78338239/224062019-f072867d-2c00-48b4-84eb-e9baf8ddbb96.png)

it should be 1.5, but is computed to 2.1

**Comment by subframe7536** [comment]
fix in v0.4.6

**Comment by dubefab** [comment]
thx a lot it looks good!!! 👍
