### ISSUE TITLE
[BUG] Tags with underscore don't get color filled

### ISSUE THREAD

**Issue by dubefab** [subframe7536/obsidian-theme-maple#26]
If I use a tag like this one in example with underscore, color is buggy.

<img width="201" alt="SC 2023-03-16 at 13 41 40@2x" src="https://user-images.githubusercontent.com/36094769/225734963-4e2b0364-9c5b-40d9-aa12-a49666947a2b.png">

**Comment by subframe7536** [comment]
done in v0.5.0
