### ISSUE TITLE
对有序列表及无序列表自定义颜色

### ISSUE THREAD

**Issue by Big4Plus** [subframe7536/obsidian-theme-maple#27]
对有序列表及无序列表自定义
比如说最基本的颜色
可以的话自定义背景或样式加上也可以

~~彩虹屁~~：审美戳到我了，非常好用及好看的主题，感谢！

**Comment by subframe7536** [comment]
可否给个示例图或者描述的更详细一些？

**Comment by Big4Plus** [comment]
> 可否给个示例图或者描述的更详细一些？

如下，对有序列表及无序列表的样式自定义颜色
![Snipaste_2023-03-27_08-55-13](https://user-images.githubusercontent.com/101388733/227816686-4e1f5405-9107-4ab1-ab1f-6047503d12a6.png)

**Comment by subframe7536** [comment]
v0.5.4完成
