### ISSUE TITLE
[BUG] 过长的代码在代码块下方依然没有出现滚动条

### ISSUE THREAD

**Issue by Marie-Yang** [subframe7536/obsidian-theme-maple#28]
Mac 13版本，obsidian 1.1.16
style setting 里勾选了“预览模式 代码块不换行”后，阅读模式下，过长的代码在代码块下方依然没有出现滚动条

<img width="748" alt="image" src="https://user-images.githubusercontent.com/97232990/233828391-1cb1c796-e552-4966-a78d-db41b70c0887.png">

**Comment by subframe7536** [comment]
无法复现🧐

**Comment by wayner6** [comment]
@subframe7536 就像这样，我勾选了代码不换行就看不到后面的代码了，也无法拖拽，即缺少横向滚动条
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/88063517/41ad8c5b-3834-47b0-becb-dbf33ca46b5b)

**Comment by subframe7536** [comment]
@wayner6 沙箱环境正常，确认是否打开了“不显示滚动条”

**Comment by wayner6** [comment]
@subframe7536 刚刚测试，无论打开还是关闭“不显示滚动条”都无法显示横向滚动条

**Comment by wayner6** [comment]
> @wayner6 沙箱环境正常，确认是否打开了“不显示滚动条”

你说的沙箱环境是指？

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/4c989a79-5aa5-4489-b191-e801ec1a43ca)
最后一个

**Comment by wayner6** [comment]
@subframe7536 我没试这个，正式版无法生效不是最重要的嘛😏

**Comment by subframe7536** [comment]
这个就是正式版
