### ISSUE TITLE
What font are you using in your theme showcase?

### ISSUE THREAD

**Issue by InstantNo0dle** [subframe7536/obsidian-theme-maple#3]
I really love what you've done with your theme here. I was just wondering what font you were using in the images on the README showing off your theme.

Thanks!

**Comment by subframe7536** [comment]
text font is Google Sans, and I make it round, monospace font is https://github.com/subframe7536/Maple-font

**Comment by subframe7536** [comment]
I merge it with [CJK font](https://github.com/subframe7536/Maple-font/blob/main/README_CN.md#maple-ui) for my normal use, you can use [fonttools](https://fonttools.readthedocs.io/en/latest/subset/index.html) to subset it

**Comment by InstantNo0dle** [comment]
Would you mind sharing your rounded edition of the google sans font?

**Comment by subframe7536** [comment]
[Maple UI subset.zip](https://github.com/subframe7536/obsidian-theme-maple/files/10799471/Maple.UI.subset.zip)
font family name: maple ui
