### ISSUE TITLE
[BUG] callout 中使用##（二级标题）后，右边的箭头不居中

### ISSUE THREAD

**Issue by AbnerPei** [subframe7536/obsidian-theme-maple#30]
<img width="846" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/11939807/b2428fc4-33c6-45c5-a9a0-2759eb499240">

**Comment by subframe7536** [comment]
已修复

**Comment by AbnerPei** [comment]
> 已修复

真实泰酷辣，官方给我的回复说不建议这样搞！你竟然解决了！

你开发的主题，泰酷辣，泰酷辣，泰酷辣，符合我的需求！
