### ISSUE TITLE
[BUG] Outline style broken due to insider build 1.3.1

### ISSUE THREAD

**Issue by cs-mshah** [subframe7536/obsidian-theme-maple#36]
**Describe the Bug**
Outline style broken due to insider build 1.3.1

**Relevant Screenshots**
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/56499208/d910f74a-d81f-4cd0-9097-5afc8fea7b47)

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [ ] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [x] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

I am using this in the border theme.

**Comment by subframe7536** [comment]
sorry but currently I have no insider access. would you please provide me the dom node structure of new outline?

**Comment by cs-mshah** [comment]
does this help: [html](https://pastebin.com/5rzmHkSx)

**Comment by subframe7536** [comment]
yes, thanks

**Comment by subframe7536** [comment]
It seems that there is no difference in the current DOM structure, so it should be a change in CSS

**Comment by cs-mshah** [comment]
The border theme fixed the issues. Thanks for the amazing CSS snippet.
