### ISSUE TITLE
highlights and bold break down

### ISSUE THREAD

**Issue by dubefab** [subframe7536/obsidian-theme-maple#37]
see image you'll understand.
<img width="243" alt="2023-05-20_20 11 49" src="https://github.com/subframe7536/obsidian-theme-maple/assets/36094769/4aa9a472-2754-446e-8315-997e17bb9448">

**Comment by subframe7536** [comment]
set the corner of highlight to 0 and everything will be ok by default

**Comment by dubefab** [comment]
what do you mean? can you share the location please
