### ISSUE TITLE
Feature Request: 关系图谱中被选中的文件用一种更加显眼的颜色

### ISSUE THREAD

**Issue by wwjCMP** [subframe7536/obsidian-theme-maple#39]
特别是暗黑模式下，被选中的文件的颜色和其他没有被标色的文件颜色太接近了

**Comment by subframe7536** [comment]
局部图谱？可以给一个复现图吗

**Comment by wwjCMP** [comment]
![Snipaste_2023-06-08_22-39-35](https://github.com/subframe7536/obsidian-theme-maple/assets/32979859/fb26862b-0aea-42e2-b5a4-706b67fe3f82)
下方红和黄中间的是选中的文件，粉和灰的混合

**Comment by wwjCMP** [comment]
![Snipaste_2023-06-24_23-35-21](https://github.com/subframe7536/obsidian-theme-maple/assets/32979859/c50c0943-34c0-4b18-bfd4-b20c0c800866)
增加的关系图谱自定义节点颜色设置没反应。经过测试把style setting 插件关闭，聚焦节点可以显示更高对比度的颜色。不清楚什么原因。上面是我的style setting的界面。或者换个思路，有没有可能更换聚焦节点的形状，比如变为五角星。

**Comment by subframe7536** [comment]
close as stale
