### ISSUE TITLE
Maybe a typo in Readme

### ISSUE THREAD

**Issue by stevenash0822** [subframe7536/obsidian-theme-maple#4]
**Describe the Bug**
Is it necessary to install **Prism Theme**, or just a typo in Readme?

**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/22290988/220513161-33343155-310e-4429-a135-20eafc24878d.png)

**Comment by subframe7536** [comment]
thanks, It's just copied and not corrected🥲
