### ISSUE TITLE
[BUG] > [!question] 中的列表数字显示不正常

### ISSUE THREAD

**Issue by jiangaq** [subframe7536/obsidian-theme-maple#41]
<img width="150" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/1873f70b-10b7-461a-abd2-009d0b8da15b">

**Comment by subframe7536** [comment]
无法复现

![image](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/3e0e5b3e-0866-4206-9059-189d5edeb162)

**Comment by jiangaq** [comment]
还没解决，会是哪里设置问题呢？

**Comment by subframe7536** [comment]
沙箱里也是这样吗

**Comment by jiangaq** [comment]
我试了关了style settings就好了，里面只装了maple的，不知道里面哪个地方是修改这个的？

**Comment by jiangaq** [comment]
关闭了就好了
最新版的

**Comment by jiangaq** [comment]
老大，您这个列表样式bug还没修复？如果关了的话就不美观了。

我看主要是列表样式的数字的样式需要能被修改，现在太胖了，所以截了一半。或者你告诉一下，哪里能改这个列表样式里数字的样式？

另外，我发现行距也过窄，如果能增加行距的设置，或者和正文的行距保持一致也可以。

**Comment by subframe7536** [comment]
行高的修改在 Maple Editor > 文字&字体&行 > 编辑器行高

列表这块我晚上花点时间重构一下

**Comment by jiangaq** [comment]
> 行高的修改在 Maple Editor > 文字&字体&行 > 编辑器行高
> 
> 列表这块我晚上花点时间重构一下

这个行高变的是正文的，列表里的行高还是没变

**Comment by subframe7536** [comment]
我本地是正常的，可以变化

你可以去沙箱仓库里试试

不行的话请提供复现视频

**Comment by jiangaq** [comment]
沙箱里好象都正常，那怎么排查？我一个个插件都关过，只有style setting关了才正常

**Comment by subframe7536** [comment]
关闭其他css片段

**Comment by jiangaq** [comment]
好象是字体大小问题，我设到22了，改小了就好了

**Comment by subframe7536** [comment]
这种属于ob的整体设计的问题了，缩放的比例变化应该由ob提供，而不应该由主题作者手动适配
