### ISSUE TITLE
编辑模式下表格显示不全

### ISSUE THREAD

**Issue by wwjCMP** [subframe7536/obsidian-theme-maple#42]
![Snipaste_2023-06-14_01-12-56](https://github.com/subframe7536/obsidian-theme-maple/assets/32979859/0fe50ae7-2518-4590-b3fd-6ff508fcaae5)

其他主题没有这个问题

**Comment by subframe7536** [comment]
下方不是有滚动条吗？

默认主题也是显示不全的啊

**Comment by wwjCMP** [comment]
![Snipaste_2023-06-24_20-40-06](https://github.com/subframe7536/obsidian-theme-maple/assets/32979859/0d0d83f9-0ecc-40b9-9dc0-6d48fb55ce9f)
默认主题

**Comment by subframe7536** [comment]
应该是因为原本的宽度刚刚好可以不出现滚动条，主题加粗了外边框导致了宽度增加

**Comment by subframe7536** [comment]
你可以试着扩大一下 Maple Editor > 背景 > 编辑器行宽

**Comment by wwjCMP** [comment]
> 应该是因为原本的宽度刚刚好可以不出现滚动条，主题加粗了外边框导致了宽度增加

如果仅仅是宽度问题的话没事了，滚动条时我关闭了
