### ISSUE TITLE
[BUG]大纲美化显示错位

### ISSUE THREAD

**Issue by Norman-h** [subframe7536/obsidian-theme-maple#44]
**Describe the Bug**
分别在24寸台式上与14寸笔记本上使用，在台式机的屏幕上显示完美，笔记本上显示错位

**Comment by subframe7536** [comment]
请提供复现图

移动端目前没有适配

**Comment by Norman-h** [comment]
> 请提供复现图
> 
<img width="148" alt="test" src="https://github.com/subframe7536/obsidian-theme-maple/assets/40519737/0ae7612a-fa18-4d59-ba18-c291081b2920">


> 移动端目前没有适配

两台设备都是Windows，区别在于屏幕大小。

**Comment by subframe7536** [comment]
obsidian和主题的版本都需要最新版，旧版无法兼容

**Comment by Norman-h** [comment]
更新到 1.3.5 版本显示不会出现错位。谢谢
