### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rocky923** [subframe7536/obsidian-theme-maple#45]
为什么我启用主题后，感觉ob运行变卡了，切换回bule topaz主题后就没这么卡了

**Comment by subframe7536** [comment]
style settings 关闭 弹出框背景模糊

**Comment by Rocky923** [comment]
> style settings 关闭 弹出框背景模糊

非常感谢回复，关闭后确实速度快了很多，这真的是一个很棒的主题

**Comment by Rocky923** [comment]
> style settings 关闭 弹出框背景模糊

关闭后，我今天再次打开ob中的笔记还是有明显的卡顿感

**Comment by subframe7536** [comment]
现开关一次试试

如果不行，关闭 为设置面板添加顶部框 试试

**Comment by Rocky923** [comment]
> 先开关一次试试
> 
> 如果不行，关闭 为设置面板添加顶部框 试试

关闭顶部框后，当时确实卡顿消失了，但是我重启ob后卡顿又出现了，是和我的什么插件冲突了吗

**Comment by subframe7536** [comment]
不清楚，没遇到过这种情况，这个问题比较玄学，因为ob不开源，所以很难找到问题所在，只能一个个试

**Comment by Rocky923** [comment]
> 不清楚，没遇到过这种情况，这个问题比较玄学，因为ob不开源，所以很难找到问题所在，只能一个个试

像是这个主题和excalidraw插件冲突了，切换主题后打开excalidraw和笔记会流畅很多

**Comment by subframe7536** [comment]
沙箱无法复现😓没法修

**Comment by subframe7536** [comment]
新版本再试试？一样的话真的没办法了

**Comment by subframe7536** [comment]
close as stale
