### ISSUE TITLE
Feature Request: TODO 的已取消和已完成样式区分

### ISSUE THREAD

**Issue by bulubin** [subframe7536/obsidian-theme-maple#46]
**Feature Requested**
TODO 的已取消和已完成样式区分度是否得变大一些

**Relevant Screenshots**
<img width="135" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/120386465/e3892cc2-ee7a-4025-9b71-efe814c23667">

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)

**Comment by subframe7536** [comment]
like this? https://github.com/Akifyss/obsidian-border#miscellaneous

**Comment by bulubin** [comment]
> like this? https://github.com/Akifyss/obsidian-border#miscellaneous

嗯嗯，是的。

**Comment by subframe7536** [comment]
直接用了🐶
