### ISSUE TITLE
[BUG] Beautiful but lagging

### ISSUE THREAD

**Issue by huachuman** [subframe7536/obsidian-theme-maple#47]
**Describe the Bug**
As soon as I activate this theme, Obsidian (both the UI and notes) is slow to respond to scrolling, hovering, etc

**In which mode does the bug occur?**
- [ x ] Reading/Preview Mode
- [ x ] Source Mode
- [ X ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [ X ] New Editor

**Which version of Obsidian are you using?**
- [ x ] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [ X ] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [ X ] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by huachuman** [comment]
Do you know a good way to take short videos and upload them on desktop?

**Comment by huachuman** [comment]
Good idea, but it didn't help

Here's what the lag looks like. I am on a Samsung Galaxy Book 2 with an i7 and this doesn't happen with other themes so I'm surprised. Could it be the integrated graphics? Is there anything else I could turn off? This is such a great theme I just wish it didn't lag.

![GIF 8-14-2023 9-53-27 AM](https://github.com/subframe7536/obsidian-theme-maple/assets/125603964/b3010274-aa3c-425e-b207-fc05b8dc5072)

**Comment by subframe7536** [comment]
dose turning off all the settings in "menu blur" and "scrollbar" makes the lagging disappear?

**Comment by huachuman** [comment]
This is very weird but right now it's not lagging. I didn't change anything.

**Comment by porobertdev** [comment]
Well, if someone else comes here in 2026 too, then know that It's quite smooth with blur enabled when restarting Obsidian in restricted mode. In my case, the biggest culprit was `floating-toc` plugin, which makes typing very slow/ laggy (the more headings & subheadings, the worse it is I think). With the default theme it doesn't really happen though. There must be some weird conflict.

**Comment by subframe7536** [comment]
It is caused by scrollbar animation in most report these year, and now the animation is disabled by default.
