### ISSUE TITLE
[BUG] 属性视图的tags属性，多个tag长宽不一致

### ISSUE THREAD

**Issue by stevenash0822** [subframe7536/obsidian-theme-maple#48]
**Describe the Bug**
属性视图的tags属性，多个tag长宽不一致

**Relevant Screenshots**
<img width="644" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/22290988/3e9149be-c2ef-4b34-aa36-dba88f0693c0">
<img width="588" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/22290988/3025fd93-8eae-433b-b037-bcb3c5184d43">

**In which mode does the bug occur?**
- Reading/Preview Mode
- Live Preview

**Which version of Obsidian are you using?**
- Public Release (Desktop) (Mac, Obsidian v1.4.5)

**Checklist**
- I have updated to the latest version of the theme (v0.6.15 Maple theme)

**Comment by subframe7536** [comment]
空行是自带的输入框换行了

其余的已添加支持
