### ISSUE TITLE
[BUG]阅读视图搜索关键词没高亮显示

### ISSUE THREAD

**Issue by prprpr** [subframe7536/obsidian-theme-maple#49]
阅读视图搜索关键词没高亮显示
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/7456783/606ab1f2-8b7b-4a16-9cfc-037faed954ca)
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/7456783/e9355ca4-e9c3-4c3e-b63f-5c708a05f88b)

**Comment by subframe7536** [comment]
无法复现

![image](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/65870aa5-119c-40b3-8f87-0606da968ebc)

**Comment by KalebZeng** [comment]
我刚也在自己的 Obsidian 上（Windows 11 22H2，Obsidian 1.4.16，Maple 0.7.6）试了下确实存在这个 Bug，默认主题下是可以高亮的，切换为 Maple 主题并点击前一个/后一个按钮时**页面会上下跳转但不会高亮关键词，不过仅限阅读视图，源码模式和实时阅览下搜索和高亮功能都是正常的**。

**Comment by subframe7536** [comment]
v0.7.7已修复
