### ISSUE TITLE
与Banners插件的兼容性问题

### ISSUE THREAD

**Issue by qinling73** [subframe7536/obsidian-theme-maple#5]
应用Maple主题后，Banners插件加入的图片在阅读模式下，出现**下移现象**，导致页面头部出现大量空白。

- Maple 版本 0.3.10
- Obsidian 版本 1.1.15

![image](https://user-images.githubusercontent.com/37439133/221081781-caa9ec6d-dfa2-44da-bb64-93276c101d34.png)

**Comment by subframe7536** [comment]
v0.3.12 修复
