### ISSUE TITLE
[BUG] Quote icon does not appear despite setting enabled.

### ISSUE THREAD

**Issue by huachuman** [subframe7536/obsidian-theme-maple#50]
**Describe the Bug**
The quote icon is gone even though the option is enabled

**Relevant Screenshots**
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/125603964/352ba4f3-7472-431e-8396-c576c3a67d3e)

**To Reproduce**
I've tried turning the plugin on and off again, turning the setting on and off, and restarting obsidian but nothing works to restore the icon.

**In which mode does the bug occur?**
- [ x  ] Reading/Preview Mode
- [ x ] Source Mode
- [ x ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
work correctly in my local machine...

whats your issue text? have you already disable other css snippets?

**Comment by huachuman** [comment]
I honestly wish developers on the whole would stop saying "works fine for me." That is so perfectly understood by pretty much everyone I cannot for the life of me understand why you would emphasize that. Of course it works fine for you. You developed it and haven't addressed this bug because it never came up. So yeah, I'm sure it works well for you.

That is pretty much the most useless statement ever made and it's infuriating when devs just keep repeating it. 

I appreciate that you're still trying to help after that statement but good god, it leaves such a bad taste in my mouth.

NEVERMIND.

I don't care anymore.

I'll just switch themes and forget about maple.

Good god.

**Comment by huachuman** [comment]
I'm sorry. Sometimes I'm just an asshole. I am trying to be better.

**Comment by huachuman** [comment]
BTW it was a snippet and I'm a total idiot and a jackass.
