### ISSUE TITLE
[BUG]大纲美化功能移植失效

### ISSUE THREAD

**Issue by YukiLx** [subframe7536/obsidian-theme-maple#52]
我觉得这个主题的大纲美化功能很棒，之前一直都是使用从这个主题中移植出来的CSS代码片段来实现这个功能。但最近可能是由于Obsidian版本更新，导致这个CSS代码片段失效，因此相应的功能也就没有了，希望开发者能够给予我一些建议或者指导，能够再次修复由于版本更新而造成的样式消失问题。
之前也是因为Obsidian版本更新而造成了样式消失，但所幸在中文论坛中看到了开发者的留言，因而能够顺利解决问题，但Obsidian最近一次版本更新之后，我暂时还没有找到比较好的方法解决该问题

**Comment by subframe7536** [comment]
我晚上看看能不能修一下

**Comment by YukiLx** [comment]
我之前是使用[大纲美化V3修复版 - 经验分享 - Obsidian 中文论坛](https://forum-zh.obsidian.md/t/topic/19837)这个帖子中提供的样式代码，解决了上一个Obsidian版本更新导致的样式失效问题。最近我发现大纲的样式再次失效，猜测可能也和ob版本更新有关系。
目前我Obsidian的版本是1.4.14，安装程序版本为1.4.13
当我发现大纲样式失效之后，我进行了以下的一些排错过程：
1、在其他库中尝试引入之前的CSS样式代码文件，排除第三方插件的影响。我在其他库中，包括sandbox库中使用之前的样式代码文件，均发现大纲样式失效
2、接着我尝试简单移植一下该主题中大纲样式部分的代码，将`theme.css`中大纲部分代码提取出来，同样发现没有什么效果
3、然后我尝试在sandbox中安装maple主题，开启大纲的引导线等设置。简单设置其中几项内容之后，发现大纲部分有引导线，但是没有`readme.md`文档中展示大纲功能的高亮和递进的引导线。

在sandbox中安装maple主题后的效果
![图片](https://github.com/subframe7536/obsidian-theme-maple/assets/43459210/337d7cad-793b-4489-a76a-10f5bd2587d9)
在StyleSetting中的关于大纲功能的部分设置
![图片](https://github.com/subframe7536/obsidian-theme-maple/assets/43459210/97ba85e9-ecc1-496f-9d04-422bbc5eba14)

**Comment by subframe7536** [comment]
感谢详细的测试~

现在最新版已修复，论坛里也发了修复的片段
