### ISSUE TITLE
[BUG]新标签页中无法正常显示PDF文件内容

### ISSUE THREAD

**Issue by KalebZeng** [subframe7536/obsidian-theme-maple#54]
**Bug 描述**
笔记内容页鼠标右键本地PDF文件链接，选择「在新标签页中打开」选项时不显示PDF文件内容

**相关截图**
截图1：
![右键选择在新标签页中打开](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/77c4e18a-019b-4912-b13f-54cae26ebcc9)

截图2，使用 Maple 主题后无法正常显示 PDF 内容：
![新标签页打开本地PDF不显示-Maple](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/79acc338-affd-4f69-aa8e-923c51cae2c7)

截图3，切换回 Obsidian 默认主题并重新执行前两步后能够正常显示（内容已打码）：
![新标签页打开本地PDF-默认主题正常-已打码](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/45a2926c-8722-4054-8c1d-83c1dde14c96)

截图4，系统信息：
![Windows规格](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/6b0134ab-b385-4929-8d20-582082f1adb3)

截图5，Obsidian 版本：
![Obsidian版本](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/e36cfc91-888f-49d5-a853-2f213ddfdd03)

截图6，Maple 主题版本：
![Maple主题版本](https://github.com/subframe7536/obsidian-theme-maple/assets/44630725/d6c3861b-a1d7-4c36-96b4-038c55c02746)

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
目前暂时无解，需要详细debug

可以先试试关闭滚动条动画

我本地关了之后会随机成功显示

**Comment by subframe7536** [comment]
似乎并不是滚动条的原因

**Comment by KalebZeng** [comment]
刚刚在 Style Settings 插件中切换了几次「Maple Workspace->滚动条->关闭滚动条动画」的开关，第一次确实能显示了，但我按下 Ctrl+P 输入「重新加载 Obsidian（不保存当前编辑内容）」后就完全不行了，确实好像跟滚动条没啥关系。

**Comment by KalebZeng** [comment]
我刚刚又更新到了 0.7.6，来回测试了多次，现在已经没问题能够正常显示了，Bug 已经被成功修复了。😁
