### ISSUE TITLE
Feature Request: 给有链接/内部链接的标题增加单独的样式设置 add style setting for title with link/internal link 

### ISSUE THREAD

**Issue by xubihang** [subframe7536/obsidian-theme-maple#55]
**Feature Requested**
由于我会将标题增加内部链接，从而在预览状态时，导致标题的字号无法被正确渲染，而展示为正文字号。
同时我希望让标题的颜色保持一致，而带链接的标题始终会被链接样式覆盖颜色，故无法让标题的颜色统一。
希望能增加功能，来单独控制带链接的标题的样式

Because I add internal links to the titles, the font size of the titles doesn't render correctly in the preview state, and it appears as regular text size. I also want to maintain consistent colors for the titles, but linked titles always have their color overridden by the link style, making it impossible to keep the title colors uniform. 
It will be useful if we can add a feature to independently control the style of linked titles.

**Relevant Screenshots**
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/873649/ab9cad8c-def5-4bc2-9645-f2e08ea1256b)

**Comment by subframe7536** [comment]
增加选项，将链接的样式跟随标题，然后保留前置icon？

**Comment by xubihang** [comment]
> 增加选项，将链接的样式跟随标题，然后保留前置icon？

从我个人需求来说，字号和颜色控制已经够用；icon样式跟随链接设置没啥问题。从通用性上来说，感觉增加一个标题中是否展示icon会更灵活一些；就是不知道实现的难度

**Comment by xubihang** [comment]
sorry 误操作…

**Comment by subframe7536** [comment]
试试 v0.7.9

**Comment by xubihang** [comment]
work like a charm. 感谢
