### ISSUE TITLE
能不能增加首行缩进

### ISSUE THREAD

**Issue by Darling012** [subframe7536/obsidian-theme-maple#59]
用增强编辑增加首行缩进，会整个文件都格式化，但可以通过复制缩进达到目的。能不能增加首行缩进的特性，直接用tab或四个空格完成缩进。

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/e0e7b999-eaa5-49cf-ac0a-25b3e2654361)

**Comment by subframe7536** [comment]
v0.7.13
