### ISSUE TITLE
用Highlightr插件时，高亮的上半部分没有变透明

### ISSUE THREAD

**Issue by jiangaq** [subframe7536/obsidian-theme-maple#60]
我不知道是不是Highlightr的问题，当我用Blue Topaz时，用Highlightr高亮文字时，只有文字的下面会被划上高亮的粗线，上半部分是透明的，maple中是上半部分也有浅色的高亮，能否修复下

Blue Topaz:
<img width="148" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/8dcc679b-1176-4a76-bac5-4804d8b968e8">

Maple:
<img width="171" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/66c8fa59-9f97-4007-b737-5c137915e514">

**Comment by subframe7536** [comment]
0.7.14 已修复

**Comment by jiangaq** [comment]
在Dark mode下，帮再修复一下：
<img width="166" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/72b89bc0-26c3-4117-81cd-a6a87731a6e4">

**Comment by jiangaq** [comment]
黑色背景能不能改成透明的？因为背景有可能不是纯黑的，同样light mode里也是要透明背景
谢谢！

<img width="186" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/87e9a733-a567-49fc-836e-2f71af477434">

**Comment by subframe7536** [comment]
无法实现

它实现方式是靠背景遮住底色实现的，改成透明就不是下划线的效果了
