### ISSUE TITLE
[BUG]strange-new-world插件弹出浮窗背景透明度无法调节影响查看

### ISSUE THREAD

**Issue by PupupupuTong** [subframe7536/obsidian-theme-maple#61]
默认透明度太高，文字重叠十分累眼，希望增加设置项

![image](https://github.com/subframe7536/obsidian-theme-maple/assets/69069739/a3176833-acd3-4a6d-8ddd-91ffebf04e0f)

**Comment by subframe7536** [comment]
打算这个部分重构一下，下个版本修复
