### ISSUE TITLE
在编辑模式下，输入“*”字符，* 后边的字符会看不见

### ISSUE THREAD

**Issue by Darling012** [subframe7536/obsidian-theme-maple#62]
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/40b398be-090d-462a-8d0d-605d777598f7)
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/f1fcf493-3a79-4b4c-9099-1dfd1d0866b6)
在阅读模式下正常
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/d5a95f87-acdf-4ac4-a5eb-18120849700d)

**Comment by Darling012** [comment]
还有个问题就是有时候点击目录上的文件夹，展开的文件夹会跟下方文件重叠，重启Obsidian可以解决。

**Comment by subframe7536** [comment]
你说的问题我都没法复现。。。

你的ob是最新版本吗？在沙箱里也是这样吗？

**Comment by Darling012** [comment]
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/07c33e45-2ba5-4c56-835d-93d8c320e575)

**Comment by Darling012** [comment]
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/93b3ff1c-3510-467b-a38c-5a7e76ee641c)
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/24786622/b1daee06-19fa-4f8d-abe5-02c13b30a9c8)
是最新的，沙箱里也会出现吞字符，不过用``包裹起来就没问题了

**Comment by subframe7536** [comment]
我晚上看看

**Comment by subframe7536** [comment]
默认主题也是吞字的，应该是预期行为

**Comment by subframe7536** [comment]
还是没法复现

**Comment by subframe7536** [comment]
沙箱
![reproduce](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/52119c58-e16c-4994-92e9-4e41cd6e585e)

**Comment by Darling012** [comment]
那可能是我本地的事😂
