### ISSUE TITLE
[BUG]Callouts内的任务复选框和列表样式冲突

### ISSUE THREAD

**Issue by mlosun** [subframe7536/obsidian-theme-maple#63]
在启用列表样式的情况下，callouts里的任务复选框会变成原点不可点击，不使用tasks插件手敲的任务也是这样

![WX20231221-153141](https://github.com/subframe7536/obsidian-theme-maple/assets/7459954/cfdbe178-2c23-4bb5-98fa-19af7cf29e35)
![WX20231221-153207](https://github.com/subframe7536/obsidian-theme-maple/assets/7459954/44ced512-048d-4b22-9a58-9b6f1a797086)

**Comment by subframe7536** [comment]
抱歉，精力有限，没有计划修复该问题
