### ISSUE TITLE
滚动条很粗和效果图不一致

### ISSUE THREAD

**Issue by silonance** [subframe7536/obsidian-theme-maple#7]
![image](https://user-images.githubusercontent.com/100808823/221144406-9d4462f5-6cf7-4b01-9162-46a4d4113aff.png)

**Comment by subframe7536** [comment]
无法复现，请确认使用的是pc端，且沙箱仓库中可以复现

**Comment by silonance** [comment]
这是Mac端来着，最新版本的Obsidian

**Comment by subframe7536** [comment]
没有mac，无法测试
请确认关闭了其他的snippets
