### ISSUE TITLE
[BUG] line numbers are broken in code blocks

### ISSUE THREAD

**Issue by Bounz** [subframe7536/obsidian-theme-maple#70]
**Describe the Bug**
When user has a long code block and scrolls it up and down, then line numbers behave incorrectly, suddenly changing by themselves.
Also there are no line numbers in Reading Mode.

**Relevant Screenshots**
Screen recording: https://github.com/subframe7536/obsidian-theme-maple/assets/3062744/8cc2c5cd-0db7-4522-a0ab-b3ac5aed3442

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Create a note with long code block
2. Enable code block line numbers
3. Scroll the note up and down

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [x] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
Yeah, it is a known issue.

According to element tree, there is no way to acchieve these feature
