### ISSUE TITLE
[BUG] 图片展示左下、右下角圆角缺损

### ISSUE THREAD

**Issue by CatCodeMe** [subframe7536/obsidian-theme-maple#71]
**Describe the Bug**

1. 使用svg、png等常见图片格式, 在编辑、预览、excalidraw等场景下有圆角缺失问题
2. 切换为默认主题或者其他主题，问题消失，排除是某个插件引发的问题

**Relevant Screenshots**
- 圆角缺失问题
<img width="123" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/11496772/55328dd0-6222-4e3e-980b-1b3d8b1c3254">

- 切换为默认主题，也就是实际的图片效果
<img width="147" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/11496772/2f8b5cad-e955-4294-849d-01d97388a962">

- 截图只截取了左下角，右下角也会有同样的问题。上半部分左上、右上角未发现缺失

**To Reproduce**

1. 任意复制图片到笔记里即可复现

**Which version of Obsidian are you using?**
- obsidian最新版 v1.5.3
- maple主题最新版 0.7.17

**tip**
- 希望提供全局设置气泡的圆角、直角的配置选项（style settings）,猜测是全局圆角引发的问题

**Comment by subframe7536** [comment]
圆角正常无缺失

![recording](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/3591cd13-7f64-4c59-892f-882aa8a67d93)
