### ISSUE TITLE
Feature Request: 希望能区分行间距和段间距，谢谢

### ISSUE THREAD

**Issue by OGGGGGG** [subframe7536/obsidian-theme-maple#73]
目前，使用一下CSS片段，并调整为1.5倍行距实现，但希望能在主题中直接实现。
另外，关于1.5倍行距，标题下划线有显示错误，具体见[72号问题](https://github.com/subframe7536/obsidian-theme-maple/issues/72)

**Comment by subframe7536** [comment]
已有选项

Maple Editor -> 文字 & 字体 & 行 -> 编辑器行高
