### ISSUE TITLE
[BUG] excalidraw和day planner的字体颜色问题

### ISSUE THREAD

**Issue by KingQ1024** [subframe7536/obsidian-theme-maple#75]
暗色模式下day plaaner的时间看不清楚：
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/58174558/36f9e7e1-e228-4b2f-a799-7dad0c9788a4)

明亮/暗色模式下 excalidraw打字的颜色和背景融合， 而且打字的颜色和最终的颜色不一样：
![image](https://github.com/subframe7536/obsidian-theme-maple/assets/58174558/57e073e8-3da4-4e68-8c00-fe5cdd5a05ea)

**Comment by subframe7536** [comment]
时间是怎么显示的？我没用过这个插件
