### ISSUE TITLE
Feature Request:  在预览模式下显示代码块的行号

### ISSUE THREAD

**Issue by magiceses** [subframe7536/obsidian-theme-maple#77]
**Feature Requested**
<img width="1099" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/50326171/873a0274-82f2-4055-8193-f15ad06abe18">
代码块在预览模式下没有行号，对于阅读代码很不方便，是否可以加个开关，在预览模式也可以显示行号？

**Comment by subframe7536** [comment]
CSS无法实现
