### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DutchPete** [subframe7536/obsidian-theme-maple#8]
**Describe the Bug**
When I open the Style Settings and click on the Maple section, that section closes after a couple of seconds automatically. This is after I updated to 0.3.13 via the community collection.

**Relevant Screenshots**

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Go to 'Settings'
2. Click on 'Style Settings'
3. Click on 'Maple', which will open the subsettings

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [ ] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop) 1.1.15
- [ ] Public Release (Mobile)
- [x] Insider Release (Desktop) 1.1.9
- [ ] Insider Release (Mobile)

**Checklist**
- [ ] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [ ] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
There's no animation properties be set in style settings panel and i can not reproduce

could you please provide a gif or video to show this bug?

**Comment by DutchPete** [comment]
https://user-images.githubusercontent.com/10794265/221366049-45233707-19b2-4608-92a5-cb7d7bd28eee.mov

**Comment by subframe7536** [comment]
maybe conflict with other snippets? have you ever try to disable all snippets or test in helper sandbox vault?

**Comment by DutchPete** [comment]
Rechecked just now, problem does not occur. May be due to the Day and Night plug-in.
Sorry to have bothered you with this.
