### ISSUE TITLE
编辑模式下输入时感觉有一点卡

### ISSUE THREAD

**Issue by jiangaq** [subframe7536/obsidian-theme-maple#82]
我打开了沙盒模式：不卡
关掉了插件：卡
插件不关情况下，切换到默认的主题：不卡

有什么方法，比如在后台能排查吗？

**Comment by jiangaq** [comment]
<img width="420" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/a1974399-4659-4b0f-9ee2-89b2461a1c66">
<img width="413" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/79e7f500-6012-4af2-b488-4c5f16311ae3">
<img width="618" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/941879ed-093c-40d3-9a37-1c8d992511a2">

这个可以给你参考下（我不知道是不是这里看排查）

**Comment by subframe7536** [comment]
试试这个：https://github.com/subframe7536/obsidian-theme-maple/issues/78#issuecomment-1960826875

**Comment by jiangaq** [comment]
还是有一点点卡

**Comment by subframe7536** [comment]
那也没啥办法了
