### ISSUE TITLE
标题颜色无法更改

### ISSUE THREAD

**Issue by jiangaq** [subframe7536/obsidian-theme-maple#83]
<img width="774" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/599a5965-1b8a-4770-ae43-06cfcecddea0">

<img width="271" alt="image" src="https://github.com/subframe7536/obsidian-theme-maple/assets/26076033/3214de45-a146-4fa3-9ce7-a5b069509e8c">

H1我改了绿色，但是实际没改，浅色模式也不行
其他H2-H6我没试

**Comment by subframe7536** [comment]
无法复现
![recording](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/f455168d-65ec-4c85-ad27-37cdcf044799)
