### ISSUE TITLE
[BUG] The list is misaligned after line break

### ISSUE THREAD

**Issue by MhaoZheng** [subframe7536/obsidian-theme-maple#86]
When using "\<br\>" in a list or when a line breaks due to long text, the beginning of the next line is not aligned with the beginning of the first line. 

![issue](https://github.com/subframe7536/obsidian-theme-maple/assets/150307800/c882009a-7193-443e-9760-916b6a6853da)

It only occurs in live preview mode and source mode but not occurs in reading mode. 

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] **The bug can be reproduced in Sandbox Vault**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
This is not a common way to break line in Markdown and I have few bandwidth to solve these potentional bugs.

Also I can not find any way to fix this issue without breaking the indent of list

Therefore, this issue will be closed
