### ISSUE TITLE
文档大纲的刷新时机存在问题

### ISSUE THREAD

**Issue by lei-ctyh** [subframe7536/obsidian-theme-maple#89]
**Describe the Bug**
当切从文章1切换成文章2之后，文档的大纲仍然为文章1的

**Relevant Screenshots**
![recording](https://github.com/subframe7536/obsidian-theme-maple/assets/63233792/7f72dbc7-4e24-4271-8986-c540e4985af5)

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. 点击进入一篇文章
2. 查看文档大纲
3. 切换至另一篇文章
4. 查看对应大纲，会发现样式没有变化

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] **The bug can be reproduced in Sandbox Vault**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
Obsidian 的问题，打开大纲页面，然后切换标签页才会刷新

**Comment by lei-ctyh** [comment]
默认的主题我似乎没有发现这个问题




啊啊啊阿磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "subframe7536/obsidian-theme-maple"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月17日(星期三) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [subframe7536/obsidian-theme-maple] 文档大纲的刷新时机存在问题 (Issue #89)





 
Obsidian 的问题，打开大纲页面，然后切换标签页才会刷新

**Comment by subframe7536** [comment]
内容是js控制的，没有源码很难debug

**Comment by subframe7536** [comment]
v0.7.28

关闭 Maple Workspace > 标签页 > 标签页切换动画

**Comment by lei-ctyh** [comment]
> v0.7.28 0.7.28 版
> 
> 关闭 Maple Workspace > 标签页 > 标签页切换动画

有用，作者大大你的主题很赞
