### ISSUE TITLE
[BUG]与Banners兼容性问题

### ISSUE THREAD

**Issue by qinling73** [subframe7536/obsidian-theme-maple#9]
**Describe the Bug**
当添加yaml语句`banner: "50 - 其他/附件/Banners/树林.jpg"`时，导致倒数第二个标题与倒数第一个标题的正文区无法进入，无论是鼠标还是键盘，都是直接进入最后一行。

**Relevant Screenshots**
![Obsidian_fZqqmZTBFR](https://user-images.githubusercontent.com/37439133/221461651-c0482480-1745-4e34-b4de-6bc896c6cc98.gif)

**To Reproduce**
1. 添加Banners插件
2. 页首加入Banner配置`banner: "50 - 其他/附件/Banners/树林.jpg"`
3. 点击倒数第二个标题和倒数第一个标题下的正文区

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by subframe7536** [comment]
fix in v0.3.15
