### ISSUE TITLE
[BUG]点击放时图片会被遮挡

### ISSUE THREAD

**Issue by x2o2** [subframe7536/obsidian-theme-maple#90]
把:active设置成position: relative;不然看着难受

**Comment by subframe7536** [comment]
Style Settings > Maple Editor > 图片 > 鼠标按下时放大图片

**Comment by x2o2** [comment]
就是设置了这个，点击放大图片会被遮挡
> [!col]
>
>> [!col-md-2]
>> ![[_resource/Pasted image 20240531114746.png]]
>> ### 7-Zip
>
>> [!col-md-2]
>> ![[_resource/Pasted image 20240531114746.png]]
>> ### 7-Zip
>
>> [!col-md-2]
>> ![[_resource/Pasted image 20240531114746.png]]
>> ### 7-Zip
>
>> [!col-md-2]
>> ![[_resource/Pasted image 20240531114746.png]]
>> ### 7-Zip
>
>> [!col-md-2]
>> ![[_resource/Pasted image 20240531114746.png]]
>> ### 7-Zip

**Comment by subframe7536** [comment]
可以关闭的

**Comment by x2o2** [comment]
https://github.com/subframe7536/obsidian-theme-maple/assets/169570210/954c3998-3466-4dc1-950b-749ed8c583d3

那你瞅瞅这是啥？

**Comment by subframe7536** [comment]
![recording](https://github.com/subframe7536/obsidian-theme-maple/assets/78338239/66c111f5-5bb0-4f9f-bb70-e8c08adfd1db)
那你瞅瞅这是啥？

**Comment by subframe7536** [comment]
Also, https://github.com/subframe7536/obsidian-theme-maple/issues/78#issuecomment-1926632404
