### ISSUE TITLE
Feature Request: 使用Style Settings改掉左侧背景问题

### ISSUE THREAD

**Issue by i-rtfsc** [subframe7536/obsidian-theme-maple#92]
![screenshot-20240613-095441](https://github.com/subframe7536/obsidian-theme-maple/assets/13032439/3c03c8d7-7886-4911-9ac4-799da6a95ffc)

开发大大你好，很喜欢你这个主题。我目前使用时遇到一些小问题，我想用 Style Settings 改掉左侧背景，但没找到是在哪里改。
如上图。

顺便建议开发大大多提供一些配色方案，特别是暗黑主题的配色。

**Comment by subframe7536** [comment]
在Maple Basic Setting内可以调整

**Comment by subframe7536** [comment]
v0.8.7 调整为 Maple Color And Animation

**Comment by i-rtfsc** [comment]
升级到 v0.8.7 了，但是调节 Maple Color And Animation 都不是改左侧背景颜色的。
我希望改的是我图1中红框圈起来的背景颜色。

**Comment by subframe7536** [comment]
目前暂不支持单独设置，只能整体调整饱和度和亮度

**Comment by i-rtfsc** [comment]
好的，谢谢。
