### ISSUE TITLE
[BUG] 代码高亮无法识别c++和c#

### ISSUE THREAD

**Issue by leevccc** [subframe7536/obsidian-theme-maple#94]
只能识别cpp和csharp无法识别c++和c#

刚转来使用这个主题，之前存的笔记里面都变成unknown language了

**Comment by leevccc** [comment]
@subframe7536  代码编辑界面好了，但是阅读模式依然是 unknown language

我看到theme.css里看到有高亮相关的设置，参照前面的修改增加了c++，可是没有用

**Comment by subframe7536** [comment]
改了一下，你再看看

**Comment by subframe7536** [comment]
需要注意的是，ob用的语法高亮库prism不支持识别 `c++` / `c#`

**Comment by leevccc** [comment]
谢谢大佬！看来暂时只能把c++替换成cpp了
