### ISSUE TITLE
Feature Request: 段落首行缩进可以在阅读视图下也生效吗？

### ISSUE THREAD

**Issue by cc1477** [subframe7536/obsidian-theme-maple#95]
还有这个段落间隔是我理解的那个段间距吗，我貌似没生效
![image](https://github.com/user-attachments/assets/5a2ce4fe-9f92-4265-a1f0-6fac03f8f1b4)
另外可以增加一个页左右边距调整的选项吗，页右边距感觉明显比左边宽
主题很好看！

**Comment by subframe7536** [comment]
右边看起来比左边宽是正常的，因为文字方向是从左往右的，左边一定是顶格的，右边经常留空，会显得空一些

**Comment by subframe7536** [comment]
间距的问题已修复，可以更新一下看看效果

**Comment by cc1477** [comment]
> 右边看起来比左边宽是正常的，因为文字方向是从左往右的，左边一定是顶格的，右边经常留空，会显得空一些

有办法居中吗？

**Comment by cc1477** [comment]
> 间距的问题已修复，可以更新一下看看效果

确实没问题了，阅读模式首行缩进可以加一下吗，更新了之后貌似阅读模式开头第一段会缩进，其他段不会缩进

**Comment by subframe7536** [comment]
没办法，段落之间必须加一个空行，不然多个段落只会渲染成单个元素，没法实现缩进

**Comment by cc1477** [comment]
> 没办法，段落之间必须加一个空行，不然多个段落只会渲染成单个元素，没法实现缩进
好吧我用这个 css 可以实现阅读模式下缩进的
````
/* === 段落-首行缩进2个字符 By Linzeal 2024/2/1更新 === */

/* 也包括段落中每个回车换行后的首行缩进 */

:is(
.markdown-source-view .cm-line:not(:is(:has(>.cm-hmd-frontmatter,>br),.HyperMD-header,.HyperMD-list-line,.HyperMD-quote,table .cm-line)), /* 编辑模式 */
.markdown-rendered :not(:is(blockquote)) > p /* 阅读模式 text-indent不支持each-line的办法 */
){
  text-indent: 2em !important;
}

.markdown-rendered :not(:is(blockquote)) > p
{
  /*text-indent: 2em each-line !important; 若支持each-line参数则用这个即可，更为简单，就无需下面的修正 */
}

/* 阅读模式下对每个回车换行后的首行缩进的修正 */
.markdown-rendered :not(:is(blockquote)) > p > br
{
  content:'';
  white-space:pre; 
}
.markdown-rendered :not(:is(blockquote)) > p > br::after
{
  content:'\000A\0009\00A0\00A0\00A0\00A0\00A0'; /* Unicode字符编码\0009表示水平制表符，\00A0表示不换行空格，可通过增减、组合搭配这两个Unicode字符来微调回车换行后的首行缩进量 */
}

/* === CSS代码结束 === */
````

**Comment by subframe7536** [comment]
也是一种思路，我实现一下吧

**Comment by subframe7536** [comment]
现在应该可以了，0.8.19

**Comment by cc1477** [comment]
> 现在应该可以了，0.8.19

可以啦！感谢大佬！话说页边距有办法令他强制居中吗，还是说只能自己手动增加左边距

**Comment by subframe7536** [comment]
用主题居中据我所知只能做到这种
![image](https://github.com/user-attachments/assets/8788988d-4ede-420d-8dbd-8d2c5a8b1c31)

**Comment by cc1477** [comment]
> 用主题居中据我所知只能做到这种
> ![image](https://github.com/user-attachments/assets/8788988d-4ede-420d-8dbd-8d2c5a8b1c31)
> 

这是用主题里面带的编辑器行宽功能实现的吗？

**Comment by subframe7536** [comment]
不是，就一行 CSS
```css
[class="cm-line"], [class="cm-active cm-line"], p { text-align: center }
```

**Comment by cc1477** [comment]
> 不是，就一行 CSS
> ```css
> [class="cm-line"], [class="cm-active cm-line"], p { text-align: center }
> ```
还是感谢大佬了我可能表达的有问题，我想的是页左右边距相同而不是每段文字居中，例如用 Export Imagle 导出时就很明显右边距比左边距宽
![mmexport1727011826927.png](https://github.com/user-attachments/assets/65af86f1-f060-4e00-a756-e02b58aa24c1)

**Comment by subframe7536** [comment]
我看起来好像没啥问题(

**Comment by cc1477** [comment]
> 我看起来好像没啥问题(

不是很明显，不过边距确实不一样，还是就这样吧，感觉 ob 折腾中文排版还是有点麻烦的，得自己整首行缩进还有首尾对齐之类的
